sudo : false

notifications:
  email: false

language: C++

compiler: 
    - gcc

cache: 
  directories:
    - programs

install:
    - ./contrib/utilities/download_clang_format

script: 
    - ./contrib/utilities/check_indentation.sh 

branches:
  only:
    - master
